[package]
name = "haqumei-jpreprocess-njd"
edition = "2024"

version = "0.1.1"
description = "Japanese text preprocessor for Text-to-Speech application (OpenJTalk rewrite in rust language)."
license = "BSD-3-Clause"
repository = "https://github.com/o24s/haqumei"
keywords = ["tts", "openjtalk", "library"]
categories = ["text-processing"]
rust-version = "1.88.0"

documentation = "https://docs.rs/haqumei-jpreprocess-njd"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
phf = { workspace = true, features = ["macros"] }

haqumei-jpreprocess-core.workspace = true
haqumei-jpreprocess-window.workspace = true

[package.metadata.upstream]
repository = "https://github.com/jpreprocess/jpreprocess"
revision = "54cf9bc2d40a5d6f25144333e9cd03fd3258a126"
