[package]
name = "haqumei-python"
version = "0.8.3"
edition = "2024"
description = "A Japanese Grapheme-to-Phoneme (G2P) library."
license = "Apache-2.0"
repository = "https://github.com/o24s/haqumei"
homepage = "https://github.com/o24s/haqumei"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
haqumei = { path = "../haqumei", features = ["embed-dictionary", "download-dictionary", "unidic-yomi"] }
haqumei-jlabel.workspace = true
pyo3 = { workspace = true, features = ["extension-module"] }

[build-dependencies]
