[package]
name = "haqumei-macros"
version = "0.1.0"
edition = "2024"
authors = ["o24s <fulmlumo@gmail.com>"]
description = "Procedural macros for the Haqumei Japanese G2P library."
license = "Apache-2.0"
repository = "https://github.com/o24s/haqumei"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.117", features = ["full"] }
quote = "1.0.45"
proc-macro2 = "1.0.106"
