name: C/C++ CI

on:
  push:
    branches: [ '1.10', '1.11']
  pull_request:
    branches: [ '1.10', '1.11' ]

jobs:
  build:
    strategy:
      matrix:
        build_type: [ Release ]
        config:
          - os: ubuntu-latest
            cc: gcc
            cxx: g++
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
          - os: macos-latest
            cc: gcc
            cxx: g++
          - os: macos-latest
            cc: clang
            cxx: clang++
          - os: windows-latest
            cc: ''
            cxx: ''

    runs-on: ${{ matrix.config.os }}

    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}

    steps:
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2.2.0
        with:
          cmake-version: '3.31.0'
      - uses: actions/checkout@v7
        with:
          repository: syoyo/hts_engine_API
          path: hts_engine_API
      - name: Build hts_engine_API
        if: runner.os != 'Windows'
        working-directory: ./hts_engine_API/src
        run: |
          cmake -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D BUILD_SHARED_LIBS=ON -S . -B build
          cmake --build build --config ${{ matrix.build_type }}
      - name: Build hts_engine_API on Windows
        if: runner.os == 'Windows'
        shell: cmd
        working-directory: ./hts_engine_API/src
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath`) do call "%%i\Common7\Tools\VsDevCmd.bat" -arch=x64
          cmake -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D BUILD_SHARED_LIBS=ON -S . -B build
          cmake --build build --config ${{ matrix.build_type }}
      - uses: actions/checkout@v7
        with:
          path: open_jtalk
      - name: Build open_jtalk
        if: runner.os != 'Windows'
        working-directory: ./open_jtalk/src
        run: |
          cmake -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D BUILD_SHARED_LIBS=ON -S . -B build
          cmake --build build --config ${{ matrix.build_type }}
      - name: Build open_jtalk on Windows
        if: runner.os == 'Windows'
        shell: cmd
        working-directory: ./open_jtalk/src
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath`) do call "%%i\Common7\Tools\VsDevCmd.bat" -arch=x64
          cmake -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D BUILD_SHARED_LIBS=ON -S . -B build
          cmake --build build --config ${{ matrix.build_type }}
