name: C/C++ CI

on:
  push:
    branches: [ '1.10', '1.11']
  pull_request:
    branches: [ '1.10', '1.11' ]

jobs:
  build:
    strategy:
      matrix:
        build_type: [ Release ]
        config:
          - os: ubuntu-latest
            cc: gcc
            cxx: g++
            cmake_generator_args: ''
            library_path: ../../hts_engine_API/src/build/lib
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
            cmake_generator_args: ''
            library_path: ../../hts_engine_API/src/build/lib
          - os: macos-latest
            cc: gcc
            cxx: g++
            cmake_generator_args: ''
            library_path: ../../hts_engine_API/src/build/lib
          - os: macos-latest
            cc: clang
            cxx: clang++
            cmake_generator_args: ''
            library_path: ../../hts_engine_API/src/build/lib
          - os: windows-latest
            cc: ''
            cxx: ''
            cmake_generator_args: '-G "Visual Studio 17 2022" -A x64'
            library_path: ../../hts_engine_API/src/build/lib/Release

    runs-on: ${{ matrix.config.os }}

    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}

    steps:
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2.2.0
        with:
          cmake-version: '3.31.0'
      - uses: actions/checkout@v7
        with:
          repository: syoyo/hts_engine_API
          path: hts_engine_API
      - name: Build hts_engine_API
        working-directory: ./hts_engine_API/src
        run: |
          cmake ${{ matrix.config.cmake_generator_args }} -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D BUILD_SHARED_LIBS=ON -S . -B build
          cmake --build build --config ${{ matrix.build_type }}
      - uses: actions/checkout@v7
        with:
          path: open_jtalk
      - name: Build open_jtalk
        working-directory: ./open_jtalk/src
        run: |
          cmake ${{ matrix.config.cmake_generator_args }} -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D BUILD_SHARED_LIBS=ON -D CMAKE_INCLUDE_PATH=../../hts_engine_API/src/include -D CMAKE_LIBRARY_PATH=${{ matrix.config.library_path }} -S . -B build
          cmake --build build --config ${{ matrix.build_type }}
