[package]
name = "haqumei"
version = "0.11.0"
edition = "2024"
authors = ["o24s <fulmlumo@gmail.com>"]
description = "Haqumei is a Japanese Grapheme-to-Phoneme (G2P) library implemented in Rust."
license = "Apache-2.0"
readme = "../README.md"
homepage = "https://github.com/o24s/haqumei"
repository = "https://github.com/o24s/haqumei"
keywords = ["japanese", "g2p", "phoneme", "nlp"]
categories = ["text-processing", "parsing"]
include = [
    "LICENSE",
    "src/*",
    "data/**",
    "LICENSE-pyopenjtalk",
    "dictionary/COPYING",
    "build.rs",
    "yomi_model/**",
]

[features]
default = ["embed-dictionary", "download-dictionary"]
embed-dictionary = []
build-dictionary = []
download-dictionary = ["embed-dictionary", "dep:reqwest", "dep:tempfile"]
serde = ["dep:serde", "haqumei-jlabel/serde", "haqumei-macros/serde"]
# 既存のビルド設定との互換性のため、空の feature として残す。
generate-bindings = []


[dependencies]
arc-swap.workspace = true
daachorse.workspace = true
dirs.workspace = true
fs4.workspace = true
haqumei-jlabel.workspace = true
haqumei-jpreprocess.workspace = true
haqumei-jpreprocess-core.workspace = true
haqumei-jpreprocess-njd.workspace = true
haqumei-jpreprocess-jpcommon.workspace = true
haqumei-jpreprocess-dictionary.workspace = true
haqumei-kanalizer.workspace = true
haqumei-macros.workspace = true
hex.workspace = true
log.workspace = true
moka.workspace = true
ndarray.workspace = true
ort.workspace = true
phf.workspace = true
rayon.workspace = true
rustc-hash.workspace = true
sha2.workspace = true
tar.workspace = true
tempfile.workspace = true
thiserror.workspace = true
unicode-normalization.workspace = true
walkdir.workspace = true
zstd.workspace = true

serde = { workspace = true, optional = true }

[build-dependencies]
haqumei-jpreprocess-dictionary.workspace = true
digest-io.workspace = true
dirs.workspace = true
hex.workspace = true
sha2.workspace = true
tar.workspace = true
zstd.workspace = true

reqwest = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }
